In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
teacher_survey = pd.read_excel('../Data/2018 _Teacher_Survey.xlsx')

In [64]:
pd.options.display.max_columns = 100

In [20]:
path = '../Data/2018_rc_data.xlsx'
xl = pd.ExcelFile(path)
sheet_names = xl.sheet_names
sheet_names

['READ ME_Instructions',
 'ACT',
 'achievement',
 'discipline',
 'chronic_absenteeism',
 'CTE',
 'dropout',
 'ELPA',
 'enrollment',
 'finance',
 'grad_rate',
 'growth',
 'growth_subjects',
 'indicator_level_grades',
 'long_term_ell',
 'overall_grades',
 'postsec_enrollment',
 'ready_grad',
 'staffing',
 'success_rate',
 'teacher_retention',
 'district_info',
 'school_info']

In [21]:
for sheetname in sheet_names:
    if sheetname == 'teacher_retention':
        vars()['df' + sheetname] = pd.read_excel(path, sheet_name= sheetname)

In [23]:
dfteacher_retention

,district_number,district_name,school_number,school_name,year,percent_retained
0,0,State of Tennessee,0,NaN,2018,90.9
1,10,Anderson County Schools,0,NaN,2018,89.5
2,10,Anderson County Schools,2,Anderson County High School,2018,95.1
3,10,NaN,3,NaN,2018,78.6
4,10,Anderson County Schools,5,Andersonville Elementary,2018,92.0
...,...,...,...,...,...,...
1887,985,Achievement School District,15,Frayser Achievement Elementary,2018,20.0
1888,985,Achievement School District,20,Whitney Achievement Elementary School,2018,38.1
1889,985,Achievement School District,25,Georgian Hills Achievement Elementary School,2018,42.9
1890,985,Achievement School District,8010,Cornerstone Prep - Lester Campus,2018,62.5
1891,985,Achievement School District,8120,Memphis Scholars Florida Kansas,2018,22.2

In [3]:
teacher_survey.head()

,Number,DistrictNo,DistrictName,SchoolNo,SchoolName,School-Level Teacher Response Rate,Item_18,Topic,FullQuestion,Prompt,...,Moderately consistent,Very consistent,I don't know,"For now, I am unconvinced that RTI2 will improve student learning in my school.","I have seen positive results, but the program needs significant improvement.",I strongly believe that RTI2 has and will continue to improve student learning.,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61
0,1,10,Anderson County,5,Andersonville Elementary,0.565217,TC_01a,School Climate and Leadership,Please indicate the extent to which you agree ...,There is an atmosphere of trust and mutual res...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,10,Anderson County,5,Andersonville Elementary,0.565217,TC_01b,School Climate and Leadership,Please indicate the extent to which you agree ...,Staff at this school have an effective process...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,10,Anderson County,5,Andersonville Elementary,0.565217,TC_01c,School Climate and Leadership,Please indicate the extent to which you agree ...,Teachers are encouraged to participate in scho...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,10,Anderson County,5,Andersonville Elementary,0.565217,TC_01d,School Climate and Leadership,Please indicate the extent to which you agree ...,The staff at this school like being here; I wo...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,10,Anderson County,5,Andersonville Elementary,0.565217,TC_01e,School Climate and Leadership,Please indicate the extent to which you agree ...,I feel appreciated for the job that I am doing.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
teacher_survey = teacher_survey.drop(['Number', 'DistrictNo', 'SchoolNo'], axis=1)

In [74]:
ts = teacher_survey[teacher_survey['Item_18'].isin(['TC_01a', 'TC_01f', 'TC_15a','TC_02b', 'TC_18h','TC_07','TC_15b', 'TC_15c','TC_15d', 'TC_08a', 'TC_08b', 'TC_08c'])]

In [75]:
ts = ts[ts['Answer_Options'].isin(['Likert Scale'])]

In [76]:
ts['Item_18'].unique()

array(['TC_01a', 'TC_01f', 'TC_02b', 'TC_08a', 'TC_08b', 'TC_08c',
       'TC_15a', 'TC_15b', 'TC_15c', 'TC_15d'], dtype=object)

In [ ]:
teacher_retention =  dfteacher_retention [['school_name', 'percent_retained']]

In [79]:
ts= ts[['DistrictName', 'SchoolName', 'Item_18','Strongly Disagree', 'Disagree', 'Agree', 'Strongly Agree']]

In [ ]:
ts.pivot(index='Item_18', columns='bbb', values=['baa', 'zzz'])

In [80]:
ts.head(50)

,DistrictName,SchoolName,Item_18,Strongly Disagree,Disagree,Agree,Strongly Agree
0,Anderson County,Andersonville Elementary,TC_01a,0.000000,0.142857,0.500000,0.357143
5,Anderson County,Andersonville Elementary,TC_01f,0.000000,0.142857,0.428571,0.428571
7,Anderson County,Andersonville Elementary,TC_02b,0.142857,0.071429,0.428571,0.357143
22,Anderson County,Andersonville Elementary,TC_08a,0.000000,0.214286,0.714286,0.071429
23,Anderson County,Andersonville Elementary,TC_08b,0.000000,0.214286,0.428571,0.357143
24,Anderson County,Andersonville Elementary,TC_08c,0.071429,0.142857,0.571429,0.214286
31,Anderson County,Andersonville Elementary,TC_15a,0.000000,0.214286,0.571429,0.214286
32,Anderson County,Andersonville Elementary,TC_15b,0.071429,0.214286,0.428571,0.285714
33,Anderson County,Andersonville Elementary,TC_15c,0.142857,0.214286,0.500000,0.142857
34,Anderson County,Andersonville Elementary,TC_15d,0.000000,0.285714,0.571429,0.142857
57,Anderson County,Briceville Elementary,TC_01a,0.250000,0.250000,0.375000,0.125000
62,Anderson County,Briceville Elementary,TC_01f,0.142857,0.142857,0.428571,0.285714
64,Anderson County,Briceville Elementary,TC_02b,0.000000,0.375000,0.375000,0.250000
79,Anderson County,Briceville Elementary,TC_08a,0.000000,0.375000,0.625000,0.000000
80,Anderson County,Briceville Elementary,TC_08b,0.000000,0.000000,0.875000,0.125000
81,Anderson County,Briceville Elementary,TC_08c,0.000000,0.125000,0.875000,0.000000
88,Anderson County,Briceville Elementary,TC_15a,0.125000,0.250000,0.500000,0.125000
89,Anderson County,Briceville Elementary,TC_15b,0.125000,0.375000,0.500000,0.000000
90,Anderson County,Briceville Elementary,TC_15c,0.125000,0.250000,0.500000,0.125000
91,Anderson County,Briceville Elementary,TC_15d,0.000000,0.375000,0.500000,0.125000
114,Anderson County,Claxton Elementary,TC_01a,0.157895,0.368421,0.315789,0.157895
119,Anderson County,Claxton Elementary,TC_01f,0.263158,0.210526,0.421053,0.105263
121,Anderson County,Claxton Elementary,TC_02b,0.315789,0.315789,0.263158,0.105263
136,Anderson County,Claxton Elementary,TC_08a,0.210526,0.473684,0.210526,0.105263
137,Anderson County,Claxton Elementary,TC_08b,0.000000,0.105263,0.736842,0.157895
138,Anderson County,Claxton Elementary,TC_08c,0.222222,0.500000,0.222222,0.055556
145,Anderson County,Claxton Elementary,TC_15a,0.052632,0.210526,0.631579,0.105263
146,Anderson County,Claxton Elementary,TC_15b,0.105263,0.315789,0.526316,0.052632
147,Anderson County,Claxton Elementary,TC_15c,0.315789,0.210526,0.315789,0.157895
148,Anderson County,Claxton Elementary,TC_15d,0.052632,0.157895,0.736842,0.052632
171,Anderson County,Clinton Middle School,TC_01a,0.130435,0.217391,0.565217,0.086957
176,Anderson County,Clinton Middle School,TC_01f,0.043478,0.173913,0.695652,0.086957
178,Anderson County,Clinton Middle School,TC_02b,0.086957,0.347826,0.434783,0.130435
193,Anderson County,Clinton Middle School,TC_08a,0.000000,0.521739,0.478261,0.000000
194,Anderson County,Clinton Middle School,TC_08b,0.000000,0.304348,0.565217,0.130435
195,Anderson County,Clinton Middle School,TC_08c,0.043478,0.391304,0.565217,0.000000
202,Anderson County,Clinton Middle School,TC_15a,0.000000,0.260870,0.652174,0.086957
203,Anderson County,Clinton Middle School,TC_15b,0.000000,0.409091,0.590909,0.000000
204,Anderson County,Clinton Middle School,TC_15c,0.045455,0.545455,0.227273,0.181818
205,Anderson County,Clinton Middle School,TC_15d,0.043478,0.391304,0.478261,0.086957
228,Anderson County,Clinton High School,TC_01a,0.000000,0.062500,0.500000,0.437500
233,Anderson County,Clinton High School,TC_01f,0.000000,0.093750,0.468750,0.437500
235,Anderson County,Clinton High School,TC_02b,0.000000,0.096774,0.354839,0.548387
250,Anderson County,Clinton High School,TC_08a,0.093750,0.375000,0.437500,0.093750
251,Anderson County,Clinton High School,TC_08b,0.000000,0.156250,0.718750,0.125000
252,Anderson County,Clinton High School,TC_08c,0.031250,0.343750,0.562500,0.062500
259,Anderson County,Clinton High School,TC_15a,0.000000,0.096774,0.483871,0.419355
260,Anderson County,Clinton High School,TC_15b,0.000000,0.200000,0.533333,0.266667
261,Anderson County,Clinton High School,TC_15c,0.000000,0.200000,0.433333,0.366667
262,Anderson County,Clinton High School,TC_15d,0.000000,0.161290,0.612903,0.225806

In [6]:
ts_long = ts.melt(id_vars =['DistrictName','SchoolName','Item_18', 'Topic'], value_vars =['Strongly Disagree', 'Disagree', 'Agree', 'Strongly Agree', '_5% or Less', '_6%-10%', '_11%-15%', '_16%-25%', 'More than 25%','I need both more PD experiences and higher quality PD in this area.','I need higher quality PD in this area.', 'I am satisfied with both the quality and amount of PD received in this area.'   ]).dropna()

In [12]:
ts_long.head()

,DistrictName,SchoolName,Item_18,Topic,variable,value
0,Anderson County,Andersonville Elementary,TC_01a,School Climate and Leadership,Strongly Disagree,0.000000
1,Anderson County,Andersonville Elementary,TC_01f,School Climate and Leadership,Strongly Disagree,0.000000
2,Anderson County,Andersonville Elementary,TC_02b,School Climate and Leadership,Strongly Disagree,0.142857
4,Anderson County,Andersonville Elementary,TC_08a,School Climate and Leadership,Strongly Disagree,0.000000
5,Anderson County,Andersonville Elementary,TC_08b,School Climate and Leadership,Strongly Disagree,0.000000

In [15]:
tc01aPos =ts_long[(ts_long['Item_18'] =='TC_01a')& (ts_long['variable'].str.contains('Agree'))]

In [26]:
tc01aPos=tc01aPos.groupby(['DistrictName','SchoolName', 'Item_18', 'Topic'])['value'].sum().reset_index()

In [33]:
tc01aPos.head()

,DistrictName,SchoolName,Item_18,Topic,value
0,Alamo,Alamo Elementary,TC_01a,School Climate and Leadership,0.585366
1,Alcoa City,Alcoa Elementary,TC_01a,School Climate and Leadership,0.823529
2,Alcoa City,Alcoa High School,TC_01a,School Climate and Leadership,1.000000
3,Alcoa City,Alcoa Intermediate School,TC_01a,School Climate and Leadership,0.923077
4,Alcoa City,Alcoa Middle School,TC_01a,School Climate and Leadership,0.928571

In [39]:
tc01aPos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1165 entries, 0 to 1164
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   DistrictName  1165 non-null   object
 1   SchoolName    1165 non-null   object
 2   Item_18       1165 non-null   object
 3   Topic         1165 non-null   object
 4   value         1165 non-null   float64
dtypes: float64(1), object(4)
memory usage: 45.6+ KB

In [48]:
dfteacher_retention['district_name']=dfteacher_retention['district_name'].str.replace(' City School District', "")

In [35]:
dfteacher_retention['district_name']=dfteacher_retention['district_name'].str.replace(' Schools', "")

In [47]:
dfteacher_retention[dfteacher_retention['district_name'].astype(str).str.contains('Alamo')]

,district_number,district_name,school_number,school_name,year,percent_retained
268,171,Alamo City School District,0,NaN,2018,85.4
269,171,Alamo City School District,5,Alamo Elementary,2018,85.1

In [57]:
teach_ret_surv= pd.merge(
left = tc01aPos, 
    right =dfteacher_retention[['district_name', 'school_name', 'percent_retained']].rename(columns = {'district_name': 'DistrictName', 'school_name':'SchoolName'} ),
)

In [81]:
All_teach_ret_surv= pd.merge(
left = ts, 
    right =dfteacher_retention[['district_name', 'school_name', 'percent_retained']].rename(columns = {'district_name': 'DistrictName', 'school_name':'SchoolName'} ),
)

In [82]:
All_teach_ret_surv.head()

,DistrictName,SchoolName,Item_18,Strongly Disagree,Disagree,Agree,Strongly Agree,percent_retained
0,Anderson County,Andersonville Elementary,TC_01a,0.000000,0.142857,0.500000,0.357143,92.0
1,Anderson County,Andersonville Elementary,TC_01f,0.000000,0.142857,0.428571,0.428571,92.0
2,Anderson County,Andersonville Elementary,TC_02b,0.142857,0.071429,0.428571,0.357143,92.0
3,Anderson County,Andersonville Elementary,TC_08a,0.000000,0.214286,0.714286,0.071429,92.0
4,Anderson County,Andersonville Elementary,TC_08b,0.000000,0.214286,0.428571,0.357143,92.0

In [56]:
teach_ret_surv[teach_ret_surv['percent_retained'].isna()]

,DistrictName,SchoolName,Item_18,Topic,value,percent_retained
5,Alvin C York Institute,Alvin C. York Institute,TC_01a,School Climate and Leadership,0.923077,NaN
16,Arlington,Arlington Elementary,TC_01a,School Climate and Leadership,1.000000,NaN
17,Arlington,Arlington High,TC_01a,School Climate and Leadership,0.787500,NaN
18,Arlington,Arlington Middle,TC_01a,School Climate and Leadership,0.891304,NaN
19,Arlington,Donelson Elementary,TC_01a,School Climate and Leadership,0.714286,NaN
...,...,...,...,...,...,...
1162,Wilson County,West Elementary,TC_01a,School Climate and Leadership,1.000000,NaN
1163,Wilson County,West Wilson Middle School,TC_01a,School Climate and Leadership,0.913043,NaN
1164,Wilson County,Wilson Central High School,TC_01a,School Climate and Leadership,0.933333,NaN
2087,Lakeland School System,NaN,NaN,NaN,NaN,NaN
2088,Lakeland School System,Lakeland Elementary School,NaN,NaN,NaN,NaN

In [52]:
teach_ret_surv.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2243 entries, 0 to 2242
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   DistrictName      2116 non-null   object
 1   SchoolName        1974 non-null   object
 2   Item_18           1165 non-null   object
 3   Topic             1165 non-null   object
 4   value             1165 non-null   float64
 5   percent_retained  1890 non-null   object
dtypes: float64(1), object(5)
memory usage: 122.7+ KB

In [61]:
teach_ret_surv['percent_retained'] = teach_ret_surv['percent_retained'].astype(float)

In [58]:
teach_ret_surv.head()

,DistrictName,SchoolName,Item_18,Topic,value,percent_retained
0,Alamo,Alamo Elementary,TC_01a,School Climate and Leadership,0.585366,85.1
1,Alcoa City,Alcoa Elementary,TC_01a,School Climate and Leadership,0.823529,97.1
2,Alcoa City,Alcoa High School,TC_01a,School Climate and Leadership,1.000000,87.8
3,Alcoa City,Alcoa Intermediate School,TC_01a,School Climate and Leadership,0.923077,86.2
4,Alcoa City,Alcoa Middle School,TC_01a,School Climate and Leadership,0.928571,96.7

In [62]:
teach_ret_surv['percent_retained'].corr(teach_ret_surv['value'])

0.20295249250792252